n = input('insira qualquer dado: ')
print('O tipo primitivo desse valor e: {}'.format(type(n)))
print('E numerico? {}'.format(n.isnumeric()))
print('E alfabetico? {}'.format(n.isalpha()))
print('E alfanumerico? {}'.format(n.isalpha()))
print('Esta em maiusculo? {}'.format(n.isupper()))
print('Esta em minuscilo? {}'.format(n.islower()))
print('So tem espaco? {}'.format(n.isspace()))
print('Esta capitalizado? {}'.format(n.istitle()))